name: Build and Publish Preview NuGet Package

on:
  push:
    branches:
      - Development
  pull_request:
    branches:
      - Development

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Adjust according to your project's target framework

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/Development'
    needs: build
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Adjust according to your project's target framework

    - name: Restore dependencies
      run: dotnet restore

    - name: Extract version from .csproj and append -preview
      id: extract-version
      shell: bash
      run: |
        VERSION=$(dotnet msbuild -nologo -property:Version Berrevoets.MonitoredBackgroundService/Berrevoets.MonitoredBackgroundService.csproj | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
        if [ -z "$VERSION" ]; then
          echo "Error: Version could not be extracted."
          exit 1
        fi
        echo "Version extracted: $VERSION-preview"
        echo "VERSION=$VERSION-preview" >> $GITHUB_ENV

    - name: Pack Preview NuGet package (with symbols)
      run: dotnet pack Berrevoets.MonitoredBackgroundService/Berrevoets.MonitoredBackgroundService.csproj --configuration Release --output "${{ github.workspace }}\output" /p:PackageVersion=${{ env.VERSION }} /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg

    - name: Publish Preview NuGet package
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push "${{ github.workspace }}\output\*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Publish Symbol Package (.snupkg)
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push "${{ github.workspace }}\output\*.snupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
